### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b'FETCH' with Redshift and FETCH

### ISSUE THREAD

**Issue by adedotua** [tlocke/pg8000#48]
Hello,
I am using pg8000 to create server side cursors on Redshift and getting the error below. The issue is similar to https://github.com/mfenniak/pg8000/issues/44. I manually commented out the FETCH from the self._commands_with_count and it works successfully. It seems FETCH did not return row count in 8.0.26 postgres server either. 
```
>>> cur.execute('declare testcur cursor for select * from table limit 10')
<pg8000.core.Cursor object at 0x7fd9e4ff85b0>
>>> cur.execute('fetch 5 from testcur')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adedotua/.local/python-3.8.3/lib/python3.8/site-packages/pg8000/core.py", line 352, in execute
    self._c.execute_unnamed(self, operation, args, self._input_oids)
  File "/home/adedotua/.local/python-3.8.3/lib/python3.8/site-packages/pg8000/core.py", line 1304, in execute_unnamed
    self.handle_messages(cursor)
  File "/home/adedotua/.local/python-3.8.3/lib/python3.8/site-packages/pg8000/core.py", line 1440, in handle_messages
    self.message_types[code](self._read(data_len - 4), cursor)
  File "/home/adedotua/.local/python-3.8.3/lib/python3.8/site-packages/pg8000/core.py", line 1414, in handle_COMMAND_COMPLETE
    row_count = int(values[-1])
ValueError: invalid literal for int() with base 10: b'FETCH'
>>> rows = cursor.fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cursor' is not defined
>>> rows = cur.fetchone()
>>> print(rows)
[2129840, '1990', None, None, None]
```
```
>>> cur.execute('declare testcur cursor for select rundate from table limit 1')
<pg8000.core.Cursor object at 0x7f6388610e80>
>>> cur.execute('fetch 5 from testcur')
<pg8000.core.Cursor object at 0x7f6388610e80>
>>> cur.__dict__
{'_c': <pg8000.core.Connection object at 0x7f63955da760>, 'arraysize': 1, '_row_count': -1, '_cached_rows': deque([[datetime.datetime(2020, 3, 26, 19, 4)]]), 'row_desc': [{'table_oid': 0, 'column_attrnum': 0, 'type_oid': 1114, 'type_size': 8, 'type_modifier': -1, 'format': 0, 'name': b'rundate', 'func': <function timestamp_in at 0x7f6388606f70>}], 'paramstyle': 'format', '_input_oids': None, 'stream': None, 'input_funcs': (<function timestamp_in at 0x7f6388606f70>,), 'input_types': []}
```

File is core.py at line 1484:

       elif key == b"server_version":
            self._server_version = LooseVersion(value.decode('ascii'))
            if self._server_version < LooseVersion('8.2.0'):
                self._commands_with_count = (
                    b"INSERT", b"DELETE", b"UPDATE", b"MOVE", b"FETCH")
            elif self._server_version < LooseVersion('9.0.0'):
                self._commands_with_count = (
                    b"INSERT", b"DELETE", b"UPDATE", b"MOVE", b"FETCH",
                    b"COPY")

**Comment by tlocke** [comment]
Hi @adedotua, Redshift isn't officially supported by pg8000, but I've removed the `FETCH` from `_command_with_count` for PostgreSQL version < 8.2.0 in the commit: https://github.com/tlocke/pg8000/commit/04d5abf1510c843d1be6e017623231b9839f633f
