### ISSUE TITLE
v1.16.6 errors on startup with SQLAlchemy 

### ISSUE THREAD

**Issue by karlmarx** [tlocke/pg8000#53]
I keep getting this error when I try to start up my FastAPI application that uses SQL alchemy with pg8000 v1.16.6 but I have no issues with 1.16.5:

Traceback (most recent call last):
  File "/Users/karlmarx/PycharmProjects/freemind/main.py", line 26, in <module>
    import crud
  File "/Users/karlmarx/PycharmProjects/freemind/crud.py", line 4, in <module>
    import main
  File "/Users/karlmarx/PycharmProjects/freemind/main.py", line 93, in <module>
    models.database.Base.metadata.create_all(bind=database.engine)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4555, in create_all
    bind._run_visitor(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2096, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2088, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 664, in __connect
    pool.dispatch.first_connect.for_modify(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1513, in go
    return once_fn(*arg, **kw)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 215, in initialize
    super(PGDialect_pg8000, self).initialize(connection)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2562, in initialize
    super(PGDialect, self).initialize(connection)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 312, in initialize
    self.server_version_info = self._get_server_version_info(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2803, in _get_server_version_info
    v = connection.execute("select version()").scalar()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1294, in _execute_context
    result = context._setup_crud_result_proxy()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1243, in _setup_crud_result_proxy
    result = self.get_result_proxy()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 1218, in get_result_proxy
    return result.ResultProxy(self)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 775, in __init__
    self._init_metadata()
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 807, in _init_metadata
    self._metadata = ResultMetaData(self, cursor_description)
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 290, in __init__
    raw = self._merge_cursor_description(
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 496, in _merge_cursor_description
    return [
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 496, in <listcomp>
    return [
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 616, in _merge_cols_by_none
    for (
  File "/Users/karlmarx/PycharmProjects/freemind/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 545, in _colnames_from_description
    colname = description_decoder(colname)
TypeError: expected bytes, str found

both my db and client settings are for utf-8.

**Comment by sbdelisle** [comment]
came here to report the same observation.

**Comment by kiran94** [comment]
I am seeing the exact same issue when creating via `connection = engine.connect()`. Additionally it's difficult to see where `v1.16.6` came from or what the changes are. 

The last commit to master on this repository was 27 days ago at the time of writing and there is no mention of this version [release notes](https://github.com/tlocke/pg8000#release-notes) or in [GitHub Releases](https://github.com/tlocke/pg8000/releases). It only shows up on [Pypi](https://pypi.org/project/pg8000/#history)

Thanks @karlmarx for opening this, I thought I was going crazy!

**Comment by tlocke** [comment]
Thanks @kiran94, I've pushed the code and release tag to GitHub now. The release 1.16.6 included a backwardly incompatible change (it now returns column names as strings rather than bytes). This change caused the SQLAlchemy pg8000 driver to fail. SQLAlchemy is in the process of being changed to cope with this. See more details here:

https://github.com/tlocke/pg8000/commit/3a2e7439ae3613367ec231218d7e0f541466d1e5#commitcomment-43174891

**Comment by lejinghu** [comment]
Seeing this issue too when running `metadata.create_all(engine)` from SQLAlchemy. Good to know it's being fixed :)

**Comment by ResidentMario** [comment]
Ah I ran into this issue as well. I filed a [StackOverflow Q&A](https://stackoverflow.com/questions/64519570/sqlalchemy-orm-call-fails-with-typeerror-expected-bytes-str-found/64519602#64519602); hopefully that will help with visibility.

**Comment by tlocke** [comment]
Looking at https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.pg8000 pg8000 is supported in SQLAlchemy 1.4.
