### ISSUE TITLE
Prepared statement fails for INSERT operation

### ISSUE THREAD

**Issue by czechnology** [tlocke/pg8000#59]
```py
>>> ps = conn.prepare("INSERT INTO record (domain_name) VALUES (:domain_name)")
>>> ps.run(domain_name="example.com")
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pg8000/core.py", line 1587, in run
    name_bin, row_desc, input_funcs = self.name_map[oids]
KeyError: (705,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/pg8000/core.py", line 1590, in run
    self.con.prepare_statement(self.operation, oids)
  File "/home/user/.local/lib/python3.7/site-packages/pg8000/core.py", line 1274, in prepare_statement
    return statement_name_bin, cursor.row_desc, cursor.input_funcs
AttributeError: 'Cursor' object has no attribute 'input_funcs'
```

I'm not entirely sure what are the `Cursor.input_funcs` for but the field is missing by default - maybe an empty tuple should be added in the `Cursor` constructor?
I was only able to run the `INSERT` prepared statement if first running e.g. a `SELECT` command, which populates the `input_funcs`.

**Comment by tlocke** [comment]
Hi @czechnology, this should be fixed in version 1.17.0. Let me know if it's still a problem though.
