### ISSUE TITLE
BrokenPipeError or struct.error does not invalidate connection in SQLAlchemy

### ISSUE THREAD

**Issue by hbusul** [tlocke/pg8000#65]
We are using pg8000 with SQLAlchemy in a docker environment. Everything works fine but while testing the application, whenever I restart the database(Postgresql) to simulate some error, the flask application cannot connect to the database. I'm getting either `BrokenPipeError` or `struct.error`. I did some digging and found your comment explaining one happens while writing and the other one happens while reading. And I also found in the README this behaviour is mentioned. Normally, SQLAlchemy has a way to handle disconnects by pre-pinging the server. It basically sends `SELECT 1` or something like that before sending the real query. But raising these exceptions seems to not invalidate the connection. Here is a sample log
```
2021-03-16 13:55:19,928 DEBUG sqlalchemy.pool.impl.QueuePool Connection <pg8000.legacy.Connection object at 0x7ff0bbac4150> checked out from pool
2021-03-16 13:55:19,928 DEBUG sqlalchemy.pool.impl.QueuePool Pool pre-ping on connection <pg8000.legacy.Connection object at 0x7ff0bbac4150>
[2021-03-16 13:55:19,929] ERROR in app: Exception on /namespaces/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_httpauth.py", line 382, in decorated
    )(f)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_httpauth.py", line 149, in decorated
    user = self.authenticate(auth, password)
  File "/usr/local/lib/python3.7/site-packages/flask_httpauth.py", line 220, in authenticate
    return self.verify_password_callback(username, client_password)
  File "./core/model.py", line 104, in verify_password
    rci. Suspendisse ac accumsan ipsum. Suspendisse auctor venenatis magna
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2684, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2771, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1652, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1503, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 738, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3066, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3112, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 781, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 648, in do_ping
    cursor.execute(self._dialect_specific_select_one)
  File "/usr/local/lib/python3.7/site-packages/pg8000/legacy.py", line 175, in execute
    self._c.execute_unnamed("begin transaction")
  File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 735, in execute_unnamed
    self.handle_messages(context)
  File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 895, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes
2021-03-16 13:55:19,933 DEBUG sqlalchemy.pool.impl.QueuePool Connection <pg8000.legacy.Connection object at 0x7ff0bbac4150> being returned to pool
2021-03-16 13:55:19,933 DEBUG sqlalchemy.pool.impl.QueuePool Connection <pg8000.legacy.Connection object at 0x7ff0bbac4150> rollback-on-return
```
So you can see that the connection is returned to the pool. The problem is that I don't want to `try-except` every DB query and invalidate the pool manually. Instead, is it possible that these two exceptions are wrapped in some other exception that invalidates the connection? Because they indicate a connection issue.

**Comment by tlocke** [comment]
Hi @hbusul, thanks for the bug report. Before changing anything we probably need input and advice from SQLAlchemy. If you're willing, I'd suggest raising an issue in their bug tracker, pointing to this bug and asking for advice on what to do. My tentative plan at this stage is to raise an `InterfaceError` in these cases, with the `cause` set to the original exception.

**Comment by hbusul** [comment]
From [SqlAlchemy documentation](https://docs.sqlalchemy.org/en/14/core/pooling.html?highlight=handle%20disconnect#more-on-invalidation) I found:

When using a Engine, the Connection.invalidate() method is the usual entrypoint to explicit invalidation. Other conditions by which a DBAPI connection might be invalidated include:
- a DBAPI exception such as [OperationalError](https://docs.sqlalchemy.org/en/14/core/exceptions.html#sqlalchemy.exc.OperationalError), raised when a method like connection.execute() is called, is detected as indicating a so-called “disconnect” condition. As the Python DBAPI provides no standard system for determining the nature of an exception, all SQLAlchemy dialects include a system called is_disconnect() which will examine the contents of an exception object, including the string message and any potential error codes included with it, in order to determine if this exception indicates that the connection is no longer usable. If this is the case, the _ConnectionFairy.invalidate() method is called and the DBAPI connection is then discarded.

I'm not experienced with DBAPI so please correct me, if I'm wrong.  I found that
```
InterfaceError
    Exception raised for errors that are related to the database interface rather than the database itself. It must be a subclass of Error. 
```
whereas
```
OperationalError
    Exception raised for errors that are related to the database's operation and not necessarily under the control of the
programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a 
memory allocation error occurred during processing, etc. It must be a subclass of DatabaseError. 
```

`OperationalError` looks like a better fit here but if it is not enough I can also open an issue in SQLAlchemy to ask them as well.

**Comment by hbusul** [comment]
I opened an issue at [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/issues/6099) to double-check that and it seems like the correct way of handling that is to wrap the exception with `OperationalError`. I hope this provides some help. Please let me know if there is anything else I can do.

**Comment by tlocke** [comment]
Reading the comments on the SQLAlchemy issue, it seems like we'd better wrap the network errors in a DBAPI exception :-) So I've done that in the change at https://github.com/tlocke/pg8000/commit/4b0a6c6734fd8483e9f15db4c5eac38937370a36 The exception that's raised is in fact the more generic `InterfaceError` because the pg8000 native interface just has the three exceptions `InterfaceError` and `DatabaseError` and their superclass `Error`.

Thanks for discovering this flaw in pg8000 @hbusul and for investigating it so thoroughly. Hopefully this change should fix things, but let me know if there's still a problem.

**Comment by hbusul** [comment]
This makes things better but does not solve the issue. I tried with an internal code but it does not invalidate the connection, here from SqlAlchemy documentation

- As the Python DBAPI provides no standard system for determining the nature of an exception, all SQLAlchemy dialects include a system called is_disconnect() which will examine the contents of an exception object, including the string message and any potential error codes included with it, in order to determine if this exception indicates that the connection is no longer usable.

In the SqlAlchemy repository, I found [pg8000.py](https://github.com/sqlalchemy/sqlalchemy/blob/640cd8a70f8a664b7834c5f74ec322fdea644043/lib/sqlalchemy/dialects/postgresql/pg8000.py). I don't know who provides this code but it includes:

``` Python
    def is_disconnect(self, e, connection, cursor):
        return "connection is closed" in str(e)
```

So [I tried](https://github.com/hbusul/pg8000) putting `connection is closed` to raised connections and it seems to do the trick.
I also opened a [pull request](https://github.com/tlocke/pg8000/pull/68) , could you take a look at this

Thanks for the fix

**Comment by tlocke** [comment]
My feeling is that we've now got pg8000 to a position where it's providing enough information for the calling code (in this case SQLAlchemy) to handle network error situations as they like. For example if SQLAlchemy decided that a connection was no longer usable after a network error, it could do the following in the `is_disconnect` function:

```
def is_disconnect(self, e, connection, cursor):
    return str(e).startswith("network error")
```
